apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  namespace: istio-system
data:
  config.yaml: |
    auth:
      openid: {}
      openshift:
        client_id_prefix: kiali
      strategy: anonymous
    deployment:
      accessible_namespaces:
      - '**'
    external_services:
      custom_dashboards:
        enabled: true
      grafana:
        enabled: true
        in_cluster_url: 'http://prometheus-grafana.monitoring:80'
        url: 'http://prometheus-grafana.monitoring:80'
      istio:
        root_namespace: istio-system
      prometheus:
        url: 'http://prometheus.istio-system:9090'
      tracing:
        enabled: true
        in_cluster_url: 'http://tracing.istio-system:80'
        url: 'http://tracing.istio-system:80'
        use_grpc: true
    istio_namespace: istio-system
    kiali_feature_flags:
      certificates_information_indicators:
        enabled: true
        secrets:
        - cacerts
        - istio-ca-secret
      clustering:
        autodetect_secrets:
          enabled: true
          label: kiali.io/multiCluster=true
        clusters: []
      disabled_features: []
      validations:
        ignore:
        - KIA1301
    login_token:
      signing_key: CHANGEME00000000
    server:
      metrics_enabled: true
      metrics_port: 9090
      port: 20001
      web_root: /kiali
