apiVersion: batch/v1
kind: CronJob
metadata:
  name: user-service-db-backup
  labels:
    app: user-service
spec:
  # 매일 자정 (UTC 기준)에 실행
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
          - name: db-backup
            # 간단한 작업을 위해 alpine 리눅스 이미지 사용
            image: alpine:latest
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                cpu: 100m
                memory: 128Mi
            # 실행할 백업 명령어
            # /data/app.db 파일을 /backup/app.db.[현재날짜] 형태로 복사
            command: ["/bin/sh", "-c"]
            args:
            - >
              apk add --no-cache tzdata &&
              cp /usr/share/zoneinfo/Asia/Seoul /etc/localtime &&
              echo "Asia/Seoul" > /etc/timezone &&
              BACKUP_FILENAME="app.db.$(date +%Y-%m-%d-%H%M%S)" &&
              echo "Backing up /data/app.db to /backup/$BACKUP_FILENAME" &&
              cp /data/app.db /backup/$BACKUP_FILENAME
            volumeMounts:
            # user-service와 동일한 PVC를 마운트
            - name: user-data
              mountPath: /data
              readOnly: true # 원본 데이터 보호를 위해 읽기 전용으로 마운트
            - name: backup-storage
              mountPath: /backup
          volumes:
          - name: user-data
            persistentVolumeClaim:
              claimName: user-service-data-pvc
          # 실제 운영 환경에서는 이 볼륨을 별도의 PV/PVC나 외부 스토리지(NFS, S3 등)로 연결해야 합니다.
          # 여기서는 간단히 user-data PVC를 재사용하여 백업 디렉터리를 만듭니다.
          - name: backup-storage
            persistentVolumeClaim:
              claimName: user-service-data-pvc
          # 재시작 정책: 실패 시 재시도 안함
          restartPolicy: OnFailure
