apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace for all resources
namespace: titanium-prod

# Name prefix for all resources
namePrefix: prod-

# Base resources
resources:
  - ../../base
  - namespace.yaml
  - configmap-patch.yaml
  - secret-patch.yaml

# Patches for Solid Cloud environment
patches:
  # Change Service type from ClusterIP to LoadBalancer for external access
  - path: patches/service-lb-patch.yaml
    target:
      kind: Service
      name: load-balancer-service

  # Remove SQLite PVC from user-service deployment
  - path: patches/user-service-deployment-patch.yaml
    target:
      kind: Deployment
      name: user-service-deployment

  # Update blog-service deployment for PostgreSQL
  - path: patches/blog-service-deployment-patch.yaml
    target:
      kind: Deployment
      name: blog-service-deployment

# ConfigMap generator for production-specific config
configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - ENVIRONMENT=production
      - POSTGRES_HOST=postgresql-service
      - POSTGRES_PORT=5432
      - POSTGRES_DB=titanium

# Secret generator (will be replaced by actual secrets)
# Note: In production, manage secrets separately or use external secret managers
secretGenerator:
  - name: app-secrets
    behavior: merge
    # Secrets will be managed via separate secret-patch.yaml

# Common labels for all resources
commonLabels:
  environment: production
  managed-by: kustomize
  project: titanium

# Images to use (update with actual registry)
images:
  - name: dongju101/titanium-user-service
    newTag: latest
  - name: dongju101/titanium-blog-service
    newTag: latest
  - name: dongju101/titanium-auth-service
    newTag: latest
  - name: dongju101/titanium-api-gateway
    newTag: latest

# Resource modifications
replicas:
  - name: user-service-deployment
    count: 2
  - name: blog-service-deployment
    count: 2
  - name: auth-service-deployment
    count: 2
  - name: api-gateway-deployment
    count: 2
