# kube-prometheus-stack values for Solid Cloud

# Prometheus 설정
prometheus:
  prometheusSpec:
    # 메트릭 수집 간격
    scrapeInterval: 30s
    # 메트릭 보관 기간
    retention: 7d
    # 스토리지 설정
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    # ServiceMonitor 자동 감지
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

  # Prometheus 외부 접근 설정 (NodePort)
  service:
    type: NodePort
    nodePort: 30090

# Grafana 설정
grafana:
  enabled: true

  # Admin 계정 설정
  adminPassword: admin123

  # Grafana 외부 접근 설정 (NodePort)
  service:
    type: NodePort
    nodePort: 30300

  # 퍼시스턴스 설정
  persistence:
    enabled: true
    size: 5Gi

  # Prometheus 데이터 소스는 Helm chart가 자동 설정
  # (kube-prometheus-stack이 자동으로 Prometheus 연결)

# AlertManager 설정
alertmanager:
  enabled: true

  # AlertManager 외부 접근 설정
  service:
    type: NodePort
    nodePort: 30093

# Node Exporter 활성화 (노드 메트릭 수집)
nodeExporter:
  enabled: true

# Kube State Metrics 활성화 (K8s 리소스 메트릭)
kubeStateMetrics:
  enabled: true

# Prometheus Operator 설정
prometheusOperator:
  enabled: true

  # Admission Webhook 비활성화 (Solid Cloud 환경)
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false

  # TLS 비활성화
  tls:
    enabled: false
