apiVersion: v1
kind: Service
metadata:
  name: load-balancer-service
spec:
  type: LoadBalancer  # Changed from ClusterIP to LoadBalancer
  # Optionally specify loadBalancerIP if you have a reserved IP
  # loadBalancerIP: "203.0.113.10"
